# NOTE: update this with your service name
service: notes-api

# Create an optimized package for our functions that considers functions separately so that cold starts are quicker
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline # Package helpful for local development
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

# Functions structure: the lambda function hello has a handler which is the hello function exported in the handler.js file
# This lambda function also responds to an http get event with the path /hello 

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
